//! Thin `uniffi` bindings for native mobile clients (Kotlin today, Swift once
//! iOS development is possible again — docs/STATUS.md).
//!
//! A marshalling layer and nothing else, on the same terms as [`crate::wasm`]:
//! no crypto decision is made here, only Kotlin/Swift
//! types in, straight into `kdf` / `keys` / `vault_item`, and back.
//!
//! # No hand-written `unsafe`
//!
//! The crate keeps `#![forbid(unsafe_code)]` with this module included: every
//! bit of `unsafe` a native FFI boundary needs is generated by the `uniffi`
//! crate itself, inside its own macro expansion, never written here. This is
//! the reason to prefer `uniffi` over a hand-rolled `cbindgen` + JNI bridge —
//! the crate's rule is that `unsafe` belongs only in "a separate, minimal,
//! documented module": with `uniffi`, that module needs none at all.
//!
//! # Keys never cross into Kotlin/Swift as values
//!
//! As with the wasm bindings, every secret is returned as an opaque
//! [`uniffi::Object`] handle — [`MasterKeyHandle`], [`VaultKeyHandle`] —
//! rather than as bytes. Unlike a `wasm_bindgen` handle, a `uniffi` object
//! *is* backed by a real finalizer (the JVM `Cleaner` uniffi's generated
//! Kotlin wires up via `AutoCloseable`), so a caller that forgets to close
//! one does not leak the key forever — but do not rely on GC timing for a
//! secret's lifetime. Call `close()` (Kotlin's `.use { }` block is the
//! natural spelling) as soon as a vault locks.
//!
//! There is no mobile equivalent of `VaultKeyHandle::exportForSessionStorage`:
//! that method exists only because a Manifest V3 background page is suspended
//! by the browser several times an hour. A native app's process memory has no
//! such lifecycle, so the vault key simply stays in a held `VaultKeyHandle`
//! until the vault locks. Persisting it past that (e.g. for biometric unlock)
//! is a later, OS-Keystore-backed design, not this module.

use crate::error::CryptoError;
use crate::kdf::{Argon2Params, MasterKey, SALT_LEN, Salt};
use crate::keys::{
    KEY_LEN, NONCE_LEN, VaultKey, WrappedVaultKey, derive_auth_key as derive_auth,
    derive_stretched_encryption_key, unwrap_vault_key as unwrap_key, wrap_vault_key as wrap_key,
};
use crate::password::{
    PasswordOptions, PasswordStrength, StrengthLevel, estimate_strength,
    generate_password as generate,
};
use crate::totp::{TotpAlgorithm, TotpParams, TotpSecret, seconds_remaining, totp_code};
use crate::vault_item::{EncryptedItem, ItemHeader, decrypt_item as decrypt, encrypt_item};
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as B64;
use std::sync::Arc;

/// The one error type this boundary exposes.
///
/// Two variants only, on purpose: [`FfiError::DecryptionFailed`] collapses
/// every cryptographic failure (wrong password, wrong key, tampered
/// ciphertext, truncated input) into one indistinguishable outcome, so this
/// side of the boundary cannot become a decryption oracle either.
/// [`FfiError::InvalidArgument`] is different in kind — it
/// reports the shape of a value the caller just supplied, never anything
/// derived from a key or a plaintext.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum FfiError {
    /// Decryption or key derivation failed. Deliberately says nothing more.
    #[error("decryption failed")]
    DecryptionFailed,
    /// A caller-supplied argument was malformed.
    #[error("invalid argument: {reason}")]
    InvalidArgument {
        /// What was wrong with the shape of the argument, never its content.
        reason: String,
    },
}

fn opaque(_error: CryptoError) -> FfiError {
    FfiError::DecryptionFailed
}

fn bad_argument(what: &str) -> FfiError {
    FfiError::InvalidArgument {
        reason: what.to_string(),
    }
}

fn decode_b64(value: &str, what: &str) -> Result<Vec<u8>, FfiError> {
    B64.decode(value).map_err(|_| bad_argument(what))
}

/// An opaque handle to a derived master key. See the module docs on closing.
#[derive(uniffi::Object)]
pub struct MasterKeyHandle(MasterKey);

// Hand-written and redacted, exactly as the key it wraps — a derived Debug
// here would print through the handle to the key material.
impl core::fmt::Debug for MasterKeyHandle {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("MasterKeyHandle([REDACTED])")
    }
}

#[uniffi::export]
impl MasterKeyHandle {}

/// An opaque handle to the vault key. See [`MasterKeyHandle`] for closing.
#[derive(uniffi::Object)]
pub struct VaultKeyHandle(VaultKey);

impl core::fmt::Debug for VaultKeyHandle {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("VaultKeyHandle([REDACTED])")
    }
}

#[uniffi::export]
impl VaultKeyHandle {}

/// Mirror of [`Argon2Params`] — a plain scalar record, `uniffi`-exportable
/// directly, unlike the fixed-size-array types below.
#[derive(uniffi::Record)]
pub struct Argon2ParamsFfi {
    /// Memory cost, in kibibytes.
    pub memory_kib: u32,
    /// Time cost — number of passes.
    pub iterations: u32,
    /// Degree of parallelism — number of lanes.
    pub parallelism: u32,
}

impl From<Argon2Params> for Argon2ParamsFfi {
    fn from(params: Argon2Params) -> Self {
        Self {
            memory_kib: params.memory_kib,
            iterations: params.iterations,
            parallelism: params.parallelism,
        }
    }
}

impl From<Argon2ParamsFfi> for Argon2Params {
    fn from(params: Argon2ParamsFfi) -> Self {
        Self {
            memory_kib: params.memory_kib,
            iterations: params.iterations,
            parallelism: params.parallelism,
        }
    }
}

/// The Argon2id cost parameters this build recommends.
///
/// Returned so a client does not hard-code them — see the identical
/// rationale on [`crate::wasm::default_argon2_params`].
#[uniffi::export]
pub fn default_argon2_params() -> Argon2ParamsFfi {
    Argon2Params::default().into()
}

/// Draws a fresh per-vault salt, base64 encoded.
#[uniffi::export]
pub fn generate_salt() -> Result<String, FfiError> {
    let salt = Salt::generate().map_err(opaque)?;
    Ok(B64.encode(salt.as_bytes()))
}

/// Derives the master key from the master password.
///
/// The returned handle keeps the key inside Rust-owned memory; nothing about
/// it reaches Kotlin or Swift.
#[uniffi::export]
pub fn derive_master_key(
    password: String,
    salt_b64: String,
    memory_kib: u32,
    iterations: u32,
    parallelism: u32,
) -> Result<Arc<MasterKeyHandle>, FfiError> {
    let salt_bytes = decode_b64(&salt_b64, "salt")?;
    if salt_bytes.len() != SALT_LEN {
        return Err(bad_argument("salt"));
    }
    let salt = Salt::from_bytes(&salt_bytes).map_err(opaque)?;

    let params = Argon2Params {
        memory_kib,
        iterations,
        parallelism,
    };

    MasterKey::derive(&password, &salt, &params)
        .map(|key| Arc::new(MasterKeyHandle(key)))
        .map_err(opaque)
}

/// Derives the auth key, base64 encoded, for sending to the server.
///
/// This is the one derived key that legitimately leaves the device. It
/// decrypts nothing: a server holding it cannot read a single vault item.
#[uniffi::export]
pub fn derive_auth_key(master_key: Arc<MasterKeyHandle>) -> Result<String, FfiError> {
    let auth_key = derive_auth(&master_key.0).map_err(opaque)?;
    Ok(B64.encode(auth_key.as_bytes()))
}

/// Generates a fresh vault key.
#[uniffi::export]
pub fn generate_vault_key() -> Result<Arc<VaultKeyHandle>, FfiError> {
    VaultKey::generate()
        .map(|key| Arc::new(VaultKeyHandle(key)))
        .map_err(opaque)
}

/// Mirror of [`WrappedVaultKey`], with the fixed-size nonce widened to a
/// plain byte vector — `uniffi` has no fixed-size-array type.
#[derive(uniffi::Record)]
pub struct WrappedVaultKeyFfi {
    /// Layout version, for forward migration.
    pub version: u8,
    /// The wrapped key plus its Poly1305 tag.
    pub ciphertext: Vec<u8>,
    /// The XChaCha20 nonce this key was wrapped under.
    pub nonce: Vec<u8>,
}

impl From<WrappedVaultKey> for WrappedVaultKeyFfi {
    fn from(wrapped: WrappedVaultKey) -> Self {
        Self {
            version: wrapped.version,
            ciphertext: wrapped.ciphertext,
            nonce: wrapped.nonce.to_vec(),
        }
    }
}

impl TryFrom<WrappedVaultKeyFfi> for WrappedVaultKey {
    type Error = FfiError;

    fn try_from(wrapped: WrappedVaultKeyFfi) -> Result<Self, FfiError> {
        let nonce: [u8; NONCE_LEN] = wrapped
            .nonce
            .as_slice()
            .try_into()
            .map_err(|_| bad_argument("wrapped vault key nonce"))?;
        Ok(Self {
            version: wrapped.version,
            ciphertext: wrapped.ciphertext,
            nonce,
        })
    }
}

/// Wraps the vault key for storage, under the key derived from the password.
///
/// The nonce is generated inside the crypto core. There is no parameter for
/// it here either — a caller who could supply one could reuse one.
#[uniffi::export]
pub fn wrap_vault_key(
    vault_key: Arc<VaultKeyHandle>,
    master_key: Arc<MasterKeyHandle>,
) -> Result<WrappedVaultKeyFfi, FfiError> {
    let stretched = derive_stretched_encryption_key(&master_key.0).map_err(opaque)?;
    let wrapped = wrap_key(&vault_key.0, &stretched).map_err(opaque)?;
    Ok(wrapped.into())
}

/// Unwraps a stored vault key.
#[uniffi::export]
pub fn unwrap_vault_key(
    wrapped: WrappedVaultKeyFfi,
    master_key: Arc<MasterKeyHandle>,
) -> Result<Arc<VaultKeyHandle>, FfiError> {
    let wrapped: WrappedVaultKey = wrapped.try_into()?;
    let stretched = derive_stretched_encryption_key(&master_key.0).map_err(opaque)?;
    unwrap_key(&wrapped, &stretched)
        .map(|key| Arc::new(VaultKeyHandle(key)))
        .map_err(opaque)
}

/// Mirror of [`EncryptedItem`], nonce widened as in [`WrappedVaultKeyFfi`].
#[derive(uniffi::Record)]
pub struct EncryptedItemFfi {
    /// Stable identifier, assigned by the client that created the item.
    pub id: String,
    /// Item type discriminator for the plaintext schema inside.
    pub item_type: String,
    /// Layout version, for forward migration.
    pub format: u8,
    /// Encrypted item content plus its Poly1305 tag.
    pub ciphertext: Vec<u8>,
    /// The XChaCha20 nonce this item was encrypted under.
    pub nonce: Vec<u8>,
    /// Monotonic revision counter. Sync uses it for optimistic concurrency.
    pub version: u64,
    /// Last modification time, Unix milliseconds.
    pub updated_at: i64,
    /// Tombstone flag.
    pub deleted: bool,
}

impl From<EncryptedItem> for EncryptedItemFfi {
    fn from(item: EncryptedItem) -> Self {
        Self {
            id: item.id,
            item_type: item.item_type,
            format: item.format,
            ciphertext: item.ciphertext,
            nonce: item.nonce.to_vec(),
            version: item.version,
            updated_at: item.updated_at,
            deleted: item.deleted,
        }
    }
}

impl TryFrom<EncryptedItemFfi> for EncryptedItem {
    type Error = FfiError;

    fn try_from(item: EncryptedItemFfi) -> Result<Self, FfiError> {
        let nonce: [u8; NONCE_LEN] = item
            .nonce
            .as_slice()
            .try_into()
            .map_err(|_| bad_argument("encrypted item nonce"))?;
        Ok(Self {
            id: item.id,
            item_type: item.item_type,
            format: item.format,
            ciphertext: item.ciphertext,
            nonce,
            version: item.version,
            updated_at: item.updated_at,
            deleted: item.deleted,
        })
    }
}

/// The plaintext metadata for an item, as supplied when encrypting it — a
/// mirror of [`ItemHeader`], which borrows its strings and so cannot cross
/// the boundary directly.
#[derive(uniffi::Record)]
pub struct ItemHeaderInput {
    /// Stable identifier for the item.
    pub id: String,
    /// Item type discriminator.
    pub item_type: String,
    /// Monotonic revision counter.
    pub version: u64,
    /// Last modification time, Unix milliseconds.
    pub updated_at: i64,
    /// Tombstone flag.
    pub deleted: bool,
}

/// Encrypts one item's already-serialized JSON content.
///
/// The header fields are bound into the authentication tag, so a server that
/// moves this ciphertext onto a different `id`, relabels its type, rolls the
/// version back or flips the tombstone produces a record that fails to
/// decrypt rather than one that decrypts as something else.
#[uniffi::export]
pub fn encrypt_item_ffi(
    plaintext_json: String,
    header: ItemHeaderInput,
    vault_key: Arc<VaultKeyHandle>,
) -> Result<EncryptedItemFfi, FfiError> {
    let item = encrypt_item(
        &plaintext_json,
        &ItemHeader {
            id: &header.id,
            item_type: &header.item_type,
            version: header.version,
            updated_at: header.updated_at,
            deleted: header.deleted,
        },
        &vault_key.0,
    )
    .map_err(opaque)?;

    Ok(item.into())
}

/// Decrypts an item back to the JSON string it was built from.
///
/// The returned string holds plaintext secrets and is the caller's to
/// discard promptly; a Kotlin/Swift `String` cannot be scrubbed.
#[uniffi::export]
pub fn decrypt_item_ffi(
    item: EncryptedItemFfi,
    vault_key: Arc<VaultKeyHandle>,
) -> Result<String, FfiError> {
    let item: EncryptedItem = item.try_into()?;
    decrypt(&item, &vault_key.0).map_err(opaque)
}

/// Mirror of [`PasswordOptions`].
#[derive(uniffi::Record)]
pub struct PasswordOptionsFfi {
    /// Number of characters.
    pub length: u32,
    /// Include `a`-`z`.
    pub lowercase: bool,
    /// Include `A`-`Z`.
    pub uppercase: bool,
    /// Include `0`-`9`.
    pub digits: bool,
    /// Include punctuation.
    pub symbols: bool,
}

impl From<PasswordOptions> for PasswordOptionsFfi {
    fn from(options: PasswordOptions) -> Self {
        Self {
            length: options.length as u32,
            lowercase: options.lowercase,
            uppercase: options.uppercase,
            digits: options.digits,
            symbols: options.symbols,
        }
    }
}

impl From<PasswordOptionsFfi> for PasswordOptions {
    fn from(options: PasswordOptionsFfi) -> Self {
        Self {
            length: options.length as usize,
            lowercase: options.lowercase,
            uppercase: options.uppercase,
            digits: options.digits,
            symbols: options.symbols,
        }
    }
}

/// The generator settings this build recommends.
#[uniffi::export]
pub fn default_password_options() -> PasswordOptionsFfi {
    PasswordOptions::default().into()
}

/// Generates a password.
///
/// Returned as a plain string because it is going into a form field. Unlike a
/// key, it is meant to be read — but it is still a secret, and a Kotlin/Swift
/// `String` cannot be scrubbed, so the caller should not hold it longer than
/// the user needs it on screen.
#[uniffi::export]
pub fn generate_password_ffi(options: PasswordOptionsFfi) -> Result<String, FfiError> {
    // Unsatisfiable settings are a caller bug and say nothing secret, so the
    // reason is reported rather than collapsed.
    generate(&options.into()).map_err(|error| match error {
        CryptoError::InvalidInput(reason) => bad_argument(&reason),
        other => opaque(other),
    })
}

/// Mirror of [`StrengthLevel`].
#[derive(uniffi::Enum)]
pub enum StrengthLevelFfi {
    /// Around eight random characters or fewer.
    VeryWeak,
    /// Nine to eleven random characters.
    Weak,
    /// Around twelve random characters.
    Fair,
    /// Around sixteen random characters.
    Strong,
    /// What the generator produces by default.
    Excellent,
}

impl From<StrengthLevel> for StrengthLevelFfi {
    fn from(level: StrengthLevel) -> Self {
        match level {
            StrengthLevel::VeryWeak => Self::VeryWeak,
            StrengthLevel::Weak => Self::Weak,
            StrengthLevel::Fair => Self::Fair,
            StrengthLevel::Strong => Self::Strong,
            StrengthLevel::Excellent => Self::Excellent,
        }
    }
}

/// Mirror of [`PasswordStrength`].
#[derive(uniffi::Record)]
pub struct PasswordStrengthFfi {
    /// Estimated bits of entropy.
    pub bits: u32,
    /// The band `bits` falls in.
    pub level: StrengthLevelFfi,
}

impl From<PasswordStrength> for PasswordStrengthFfi {
    fn from(strength: PasswordStrength) -> Self {
        Self {
            bits: strength.bits,
            level: strength.level.into(),
        }
    }
}

/// Estimates how strong a password looks. Never fails — see
/// [`crate::password::estimate_strength`] for what this does and does not
/// score.
#[uniffi::export]
pub fn estimate_strength_ffi(password: String) -> PasswordStrengthFfi {
    estimate_strength(&password).into()
}

/// Length of a key in bytes, exported so a caller can validate without
/// hard-coding it.
#[uniffi::export]
pub fn key_length() -> u32 {
    KEY_LEN as u32
}

/// Reads the parameters a caller supplied for a one-time password.
fn totp_arguments(
    algorithm: &str,
    digits: u32,
    period: f64,
    unix_seconds: f64,
) -> Result<(TotpParams, u64), FfiError> {
    let params = TotpParams {
        algorithm: TotpAlgorithm::parse(algorithm).map_err(|_| bad_argument("TOTP algorithm"))?,
        digits,
        period: period.max(0.0) as u64,
    };
    Ok((params, unix_seconds.max(0.0) as u64))
}

/// The one-time code for a moment in time.
///
/// The shared secret arrives as the base32 an issuer printed, and the moment
/// as seconds since the epoch — this layer has no clock of its own, and
/// neither does the module underneath it.
#[uniffi::export]
pub fn totp_code_ffi(
    secret_b32: String,
    algorithm: String,
    digits: u32,
    period: f64,
    unix_seconds: f64,
) -> Result<String, FfiError> {
    let (params, at) = totp_arguments(&algorithm, digits, period, unix_seconds)?;
    // A malformed secret is reported as the argument problem it is. Nothing
    // derived from the secret crosses back.
    let secret = TotpSecret::parse(&secret_b32).map_err(|_| bad_argument("TOTP secret"))?;
    totp_code(&secret, &params, at).map_err(|_| bad_argument("TOTP parameters"))
}

/// How many seconds the current code has left.
#[uniffi::export]
pub fn totp_seconds_remaining_ffi(period: f64, unix_seconds: f64) -> Result<f64, FfiError> {
    let (params, at) = totp_arguments("SHA1", TotpParams::default().digits, period, unix_seconds)?;
    let left = seconds_remaining(&params, at).map_err(|_| bad_argument("TOTP period"))?;
    Ok(left as f64)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Round-trip and failure-mode coverage lives in `kdf`, `keys` and
    // `vault_item` already; these tests exist only to pin the marshalling
    // this module adds — base64 salts, nonce widening, and the two-variant
    // error collapse — the same division of labour as `tests/wasm.rs`.

    #[test]
    fn derive_master_key_round_trips_through_base64_salt() {
        let salt_b64 = generate_salt().expect("salt generation cannot fail");
        let params = default_argon2_params();

        let a = derive_master_key(
            "correct horse battery staple".to_string(),
            salt_b64.clone(),
            params.memory_kib,
            params.iterations,
            params.parallelism,
        )
        .expect("derivation with a valid salt must succeed");
        let b = derive_master_key(
            "correct horse battery staple".to_string(),
            salt_b64,
            params.memory_kib,
            params.iterations,
            params.parallelism,
        )
        .expect("derivation with a valid salt must succeed");

        // Handles are opaque, so equality is checked the only way available
        // at this boundary: the auth key each derives downstream.
        assert_eq!(derive_auth_key(a).unwrap(), derive_auth_key(b).unwrap());
    }

    #[test]
    fn malformed_salt_is_an_invalid_argument_not_a_decryption_failure() {
        let params = default_argon2_params();
        let err = derive_master_key(
            "correct horse battery staple".to_string(),
            "not base64!!".to_string(),
            params.memory_kib,
            params.iterations,
            params.parallelism,
        )
        .unwrap_err();

        assert!(matches!(err, FfiError::InvalidArgument { .. }));
    }

    #[test]
    fn wrap_unwrap_round_trips_through_the_widened_nonce() {
        let master = derive_master_key(
            "correct horse battery staple".to_string(),
            generate_salt().unwrap(),
            default_argon2_params().memory_kib,
            default_argon2_params().iterations,
            default_argon2_params().parallelism,
        )
        .unwrap();
        let vault_key = generate_vault_key().unwrap();

        let wrapped = wrap_vault_key(vault_key, master.clone()).unwrap();
        assert_eq!(wrapped.nonce.len(), NONCE_LEN);

        unwrap_vault_key(wrapped, master).expect("unwrap with the same master key must succeed");
    }

    #[test]
    fn truncated_nonce_is_an_invalid_argument() {
        let master = derive_master_key(
            "correct horse battery staple".to_string(),
            generate_salt().unwrap(),
            default_argon2_params().memory_kib,
            default_argon2_params().iterations,
            default_argon2_params().parallelism,
        )
        .unwrap();
        let vault_key = generate_vault_key().unwrap();
        let mut wrapped = wrap_vault_key(vault_key, master.clone()).unwrap();
        wrapped.nonce.pop();

        let err = unwrap_vault_key(wrapped, master).unwrap_err();
        assert!(matches!(err, FfiError::InvalidArgument { .. }));
    }

    #[test]
    fn encrypt_decrypt_round_trips_an_item() {
        let vault_key = generate_vault_key().unwrap();
        let header = ItemHeaderInput {
            id: "item-1".to_string(),
            item_type: "login".to_string(),
            version: 1,
            updated_at: 0,
            deleted: false,
        };

        let encrypted =
            encrypt_item_ffi(r#"{"secret":true}"#.to_string(), header, vault_key.clone()).unwrap();
        let plaintext = decrypt_item_ffi(encrypted, vault_key).unwrap();

        assert_eq!(plaintext, r#"{"secret":true}"#);
    }

    #[test]
    fn wrong_vault_key_is_a_decryption_failure_not_an_invalid_argument() {
        let vault_key = generate_vault_key().unwrap();
        let other_vault_key = generate_vault_key().unwrap();
        let header = ItemHeaderInput {
            id: "item-1".to_string(),
            item_type: "login".to_string(),
            version: 1,
            updated_at: 0,
            deleted: false,
        };

        let encrypted =
            encrypt_item_ffi(r#"{"secret":true}"#.to_string(), header, vault_key).unwrap();
        let err = decrypt_item_ffi(encrypted, other_vault_key).unwrap_err();

        assert!(matches!(err, FfiError::DecryptionFailed));
    }
}
