//! Master password → master key (Argon2id).
//!
//! The master key is the root of the hierarchy: it never leaves the device
//! and is never transmitted. Everything else is derived from it.

use crate::error::{CryptoError, Result};
use crate::secret::define_secret_key;
use argon2::{Algorithm, Argon2, Version};
use rand::TryRng as _;
use rand::rngs::SysRng;
use serde::{Deserialize, Serialize};
use zeroize::Zeroize as _;

/// Length of a KDF salt, in bytes.
pub const SALT_LEN: usize = 16;

/// Length of the derived master key, in bytes.
pub const MASTER_KEY_LEN: usize = 32;

/// Argon2id cost parameters.
///
/// These are persisted alongside the vault rather than hardcoded at the read
/// path, so costs can be raised later without breaking existing vaults.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct Argon2Params {
    /// Memory cost, in kibibytes.
    pub memory_kib: u32,
    /// Time cost — number of passes.
    pub iterations: u32,
    /// Degree of parallelism — number of lanes.
    pub parallelism: u32,
}

/// OWASP's Argon2id floor for interactive login (19 MiB, t=2, p=1).
///
/// This is a *minimum*, not our default. It targets roughly 100 ms of
/// server-side verification; a vault master key protects far more than a
/// single account login and is derived once per unlock, so it can afford
/// more. Rejecting anything below this floor guards against a vault written
/// with accidentally weak parameters.
pub const MIN_MEMORY_KIB: u32 = 19 * 1024;
/// Minimum accepted time cost. See [`MIN_MEMORY_KIB`].
pub const MIN_ITERATIONS: u32 = 2;

impl Default for Argon2Params {
    /// 64 MiB, 3 passes, 4 lanes.
    ///
    /// Chosen above the OWASP floor because this key is derived once per
    /// unlock, not once per request, and it is the only thing standing
    /// between an offline copy of the vault and its plaintext. 64 MiB stays
    /// within reach of a mid-range phone and of WASM's memory budget in a
    /// browser tab, which is the real constraint here — see PROJECT.md
    /// phases 2 and 4.
    ///
    /// Confirm against measured unlock latency on the slowest target device
    /// before phase 4 ships; raise if there is headroom.
    fn default() -> Self {
        Self {
            memory_kib: 64 * 1024,
            iterations: 3,
            parallelism: 4,
        }
    }
}

impl Argon2Params {
    /// Rejects parameters weaker than the OWASP floor, or structurally
    /// invalid ones.
    ///
    /// Reports the offending value: cost parameters are public, not secret.
    pub fn validate(&self) -> Result<()> {
        if self.memory_kib < MIN_MEMORY_KIB {
            return Err(CryptoError::InvalidInput(format!(
                "memory_kib {} is below the minimum of {MIN_MEMORY_KIB}",
                self.memory_kib
            )));
        }
        if self.iterations < MIN_ITERATIONS {
            return Err(CryptoError::InvalidInput(format!(
                "iterations {} is below the minimum of {MIN_ITERATIONS}",
                self.iterations
            )));
        }
        if self.parallelism == 0 {
            return Err(CryptoError::InvalidInput(
                "parallelism must be at least 1".to_owned(),
            ));
        }
        Ok(())
    }
}

/// A per-vault KDF salt.
///
/// Not secret — it is stored in the clear next to the vault — but it must be
/// unique per vault and generated by a CSPRNG.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Salt([u8; SALT_LEN]);

impl Salt {
    /// Draws a fresh salt from the OS CSPRNG.
    pub fn generate() -> Result<Self> {
        let mut bytes = [0u8; SALT_LEN];
        SysRng.try_fill_bytes(&mut bytes).map_err(|_| {
            CryptoError::KeyDerivationFailed("OS random number generator unavailable".to_owned())
        })?;
        Ok(Self(bytes))
    }

    /// Reads a salt back from storage.
    ///
    /// Reports only the length mismatch, never the bytes.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        let bytes: [u8; SALT_LEN] = bytes.try_into().map_err(|_| {
            CryptoError::InvalidInput(format!(
                "salt must be {SALT_LEN} bytes, got {}",
                bytes.len()
            ))
        })?;
        Ok(Self(bytes))
    }

    /// Borrows the salt bytes.
    pub fn as_bytes(&self) -> &[u8; SALT_LEN] {
        &self.0
    }
}

define_secret_key! {
    /// The key derived from the master password. Never leaves the device and
    /// is never transmitted; everything else in the hierarchy hangs off it.
    MasterKey, MASTER_KEY_LEN
}

impl MasterKey {
    /// Derives the master key from the master password with Argon2id.
    ///
    /// Deterministic: the same password, salt and parameters always yield the
    /// same key, which is what lets a vault be unlocked on any device without
    /// the key ever being stored or sent anywhere.
    ///
    /// The caller owns the password buffer and is responsible for scrubbing
    /// it; this function scrubs everything it derives itself.
    ///
    /// # Errors
    ///
    /// [`CryptoError::InvalidInput`] if `params` fall below the OWASP floor,
    /// [`CryptoError::KeyDerivationFailed`] if Argon2 rejects the parameters
    /// or cannot allocate its memory block. Neither message contains the
    /// password or the derived key.
    pub fn derive(password: &str, salt: &Salt, params: &Argon2Params) -> Result<Self> {
        params.validate()?;

        let argon2_params = argon2::Params::new(
            params.memory_kib,
            params.iterations,
            params.parallelism,
            Some(MASTER_KEY_LEN),
        )
        .map_err(|e| {
            CryptoError::KeyDerivationFailed(format!("Argon2 rejected the parameters: {e}"))
        })?;

        let argon2 = Argon2::new(Algorithm::Argon2id, Version::V0x13, argon2_params);

        let mut output = [0u8; MASTER_KEY_LEN];
        // The error is swallowed deliberately: argon2's failure modes here are
        // memory allocation and parameter shape, and neither is worth risking
        // a message that quotes caller-supplied bytes.
        argon2
            .hash_password_into(password.as_bytes(), salt.as_bytes(), &mut output)
            .map_err(|_| CryptoError::KeyDerivationFailed("Argon2id hashing failed".to_owned()))?;

        let key = Self::from_bytes(output);
        output.zeroize();
        Ok(key)
    }
}

// Host-only: these exercise the algorithms, which are target-independent.
// The browser-side surface is covered by tests/wasm.rs.
#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests {
    use super::*;
    use crate::test_util::hex;

    /// Test-only password. Never use a real one, even locally.
    const TEST_PASSWORD: &str = "correct horse battery staple";
    const TEST_SALT_HEX: &str = "000102030405060708090a0b0c0d0e0f";

    fn test_salt() -> Salt {
        Salt::from_bytes(&hex::<SALT_LEN>(TEST_SALT_HEX)).unwrap()
    }

    #[test]
    fn default_params_clear_the_owasp_floor() {
        let params = Argon2Params::default();
        params.validate().unwrap();
        assert!(params.memory_kib >= MIN_MEMORY_KIB);
        assert!(params.iterations >= MIN_ITERATIONS);
    }

    #[test]
    fn weak_params_are_rejected() {
        let weak = Argon2Params {
            memory_kib: 1024,
            iterations: 1,
            parallelism: 0,
        };
        assert!(weak.validate().is_err());
    }

    #[test]
    fn generated_salts_differ() {
        let a = Salt::generate().unwrap();
        let b = Salt::generate().unwrap();
        assert_ne!(a, b, "two CSPRNG salts must not collide");
    }

    #[test]
    fn salt_round_trips_through_bytes() {
        let salt = Salt::generate().unwrap();
        let restored = Salt::from_bytes(salt.as_bytes()).unwrap();
        assert_eq!(salt, restored);
    }

    #[test]
    fn salt_rejects_wrong_length() {
        assert!(Salt::from_bytes(&[0u8; SALT_LEN - 1]).is_err());
        assert!(Salt::from_bytes(&[0u8; SALT_LEN + 1]).is_err());
    }

    #[test]
    fn master_key_debug_is_redacted() {
        let key = MasterKey::from_bytes([7u8; MASTER_KEY_LEN]);
        let rendered = format!("{key:?}");
        assert_eq!(rendered, "MasterKey([REDACTED])");
        assert!(!rendered.contains('7'));
    }

    // --- Known-answer vectors ---
    //
    // The expected value below was computed by OpenSSL 3.6.3's ARGON2ID KDF,
    // not by this crate, so the test compares us against an independent
    // implementation rather than against our own output. That same OpenSSL
    // build reproduces the RFC 9106 Argon2id test vector exactly, which is
    // what earns it the role of reference here:
    //
    //   openssl kdf -keylen 32 -binary ARGON2ID \
    //     -kdfopt pass:'correct horse battery staple' \
    //     -kdfopt hexsalt:000102030405060708090a0b0c0d0e0f \
    //     -kdfopt iter:3 -kdfopt memcost:65536 -kdfopt lanes:4 -kdfopt threads:1
    //
    // If this test fails, the master key derivation changed. Every existing
    // vault is then undecryptable — treat it as a migration, never as a test
    // to update.

    #[test]
    fn master_key_matches_known_answer_vector() {
        let expected = hex::<MASTER_KEY_LEN>(
            "853b272a44db1421c02962669a55eb0994f3cab385ed1c4c79253eee19bab49e",
        );
        let key = MasterKey::derive(TEST_PASSWORD, &test_salt(), &Argon2Params::default()).unwrap();
        assert_eq!(key.as_bytes(), &expected);
    }

    #[test]
    fn argon2_crate_matches_independent_implementation() {
        // Pins the dependency itself, at cheap parameters so it runs fast.
        // RFC 9106's published vector cannot be used directly: it mixes in a
        // secret and associated data, and argon2 0.5.3 exposes no way to pass
        // associated data. This vector is OpenSSL's output at the RFC's cost
        // parameters with those two inputs omitted:
        //
        //   openssl kdf -keylen 32 -binary ARGON2ID \
        //     -kdfopt hexpass:0101..01 -kdfopt hexsalt:0202..02 \
        //     -kdfopt iter:3 -kdfopt memcost:32 -kdfopt lanes:4 -kdfopt threads:1
        //
        // A bump to the argon2 crate that changes behaviour fails here, with
        // an unambiguous cause and without dragging the vault vector with it.
        let params = argon2::Params::new(32, 3, 4, Some(32)).unwrap();
        let argon2 = Argon2::new(Algorithm::Argon2id, Version::V0x13, params);
        let mut out = [0u8; 32];
        argon2
            .hash_password_into(&[0x01; 32], &[0x02; 16], &mut out)
            .unwrap();
        assert_eq!(
            out,
            hex::<32>("03aab965c12001c9d7d0d2de33192c0494b684bb148196d73c1df1acaf6d0c2e")
        );
    }

    // --- Derivation behaviour ---

    #[test]
    fn derivation_is_deterministic() {
        let params = Argon2Params::default();
        let a = MasterKey::derive(TEST_PASSWORD, &test_salt(), &params).unwrap();
        let b = MasterKey::derive(TEST_PASSWORD, &test_salt(), &params).unwrap();
        assert!(a.ct_eq(&b), "same password and salt must give the same key");
    }

    #[test]
    fn different_salt_gives_different_key() {
        let params = Argon2Params::default();
        let other = Salt::from_bytes(&[0xFF; SALT_LEN]).unwrap();
        let a = MasterKey::derive(TEST_PASSWORD, &test_salt(), &params).unwrap();
        let b = MasterKey::derive(TEST_PASSWORD, &other, &params).unwrap();
        assert!(!a.ct_eq(&b));
    }

    #[test]
    fn different_password_gives_different_key() {
        let params = Argon2Params::default();
        let a = MasterKey::derive(TEST_PASSWORD, &test_salt(), &params).unwrap();
        let b = MasterKey::derive("correct horse battery stapl", &test_salt(), &params).unwrap();
        assert!(!a.ct_eq(&b));
    }

    #[test]
    fn different_params_give_different_key() {
        let a = MasterKey::derive(TEST_PASSWORD, &test_salt(), &Argon2Params::default()).unwrap();
        let stronger = Argon2Params {
            iterations: 4,
            ..Argon2Params::default()
        };
        let b = MasterKey::derive(TEST_PASSWORD, &test_salt(), &stronger).unwrap();
        assert!(
            !a.ct_eq(&b),
            "cost parameters must feed into the derivation"
        );
    }

    #[test]
    fn empty_password_still_derives() {
        // Enforcing password strength is the client's job, not the KDF's;
        // this must not panic.
        MasterKey::derive("", &test_salt(), &Argon2Params::default()).unwrap();
    }

    #[test]
    fn derivation_rejects_params_below_the_floor() {
        let weak = Argon2Params {
            memory_kib: 1024,
            iterations: 1,
            parallelism: 1,
        };
        let err = MasterKey::derive(TEST_PASSWORD, &test_salt(), &weak).unwrap_err();
        assert!(matches!(err, CryptoError::InvalidInput(_)));
    }

    #[test]
    fn derivation_errors_never_echo_the_password() {
        let weak = Argon2Params {
            memory_kib: 1,
            iterations: 1,
            parallelism: 1,
        };
        let message = MasterKey::derive(TEST_PASSWORD, &test_salt(), &weak)
            .unwrap_err()
            .to_string();
        assert!(!message.contains("correct horse"));
        assert!(!message.contains(TEST_SALT_HEX));
    }
}
