//! Master password → master key (Argon2id).
//!
//! Status: parameters and salt handling are implemented. `MasterKey::derive`
//! is not yet — see the TODO at the bottom of this module.

use crate::error::{CryptoError, Result};
use crate::secret::define_secret_key;
use rand::TryRng as _;
use rand::rngs::SysRng;
use serde::{Deserialize, Serialize};

/// Length of a KDF salt, in bytes.
pub const SALT_LEN: usize = 16;

/// Length of the derived master key, in bytes.
pub const MASTER_KEY_LEN: usize = 32;

/// Argon2id cost parameters.
///
/// These are persisted alongside the vault rather than hardcoded at the read
/// path, so costs can be raised later without breaking existing vaults
/// (CLAUDE.md §4.10).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct Argon2Params {
    /// Memory cost, in kibibytes.
    pub memory_kib: u32,
    /// Time cost — number of passes.
    pub iterations: u32,
    /// Degree of parallelism — number of lanes.
    pub parallelism: u32,
}

/// OWASP's Argon2id floor for interactive login (19 MiB, t=2, p=1).
///
/// This is a *minimum*, not our default. It targets roughly 100 ms of
/// server-side verification; a vault master key protects far more than a
/// single account login and is derived once per unlock, so it can afford
/// more. Rejecting anything below this floor guards against a vault written
/// with accidentally weak parameters.
pub const MIN_MEMORY_KIB: u32 = 19 * 1024;
/// Minimum accepted time cost. See [`MIN_MEMORY_KIB`].
pub const MIN_ITERATIONS: u32 = 2;

impl Default for Argon2Params {
    /// 64 MiB, 3 passes, 4 lanes.
    ///
    /// Chosen above the OWASP floor because this key is derived once per
    /// unlock, not once per request, and it is the only thing standing
    /// between an offline copy of the vault and its plaintext. 64 MiB stays
    /// within reach of a mid-range phone and of WASM's memory budget in a
    /// browser tab, which is the real constraint here — see PROJECT.md
    /// phases 2 and 4.
    ///
    /// Confirm against measured unlock latency on the slowest target device
    /// before phase 4 ships; raise if there is headroom.
    fn default() -> Self {
        Self {
            memory_kib: 64 * 1024,
            iterations: 3,
            parallelism: 4,
        }
    }
}

impl Argon2Params {
    /// Rejects parameters weaker than the OWASP floor, or structurally
    /// invalid ones.
    ///
    /// Reports the offending value: cost parameters are public, not secret.
    pub fn validate(&self) -> Result<()> {
        if self.memory_kib < MIN_MEMORY_KIB {
            return Err(CryptoError::InvalidInput(format!(
                "memory_kib {} is below the minimum of {MIN_MEMORY_KIB}",
                self.memory_kib
            )));
        }
        if self.iterations < MIN_ITERATIONS {
            return Err(CryptoError::InvalidInput(format!(
                "iterations {} is below the minimum of {MIN_ITERATIONS}",
                self.iterations
            )));
        }
        if self.parallelism == 0 {
            return Err(CryptoError::InvalidInput(
                "parallelism must be at least 1".to_owned(),
            ));
        }
        Ok(())
    }
}

/// A per-vault KDF salt.
///
/// Not secret — it is stored in the clear next to the vault — but it must be
/// unique per vault and generated by a CSPRNG.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Salt([u8; SALT_LEN]);

impl Salt {
    /// Draws a fresh salt from the OS CSPRNG.
    pub fn generate() -> Result<Self> {
        let mut bytes = [0u8; SALT_LEN];
        SysRng.try_fill_bytes(&mut bytes).map_err(|_| {
            CryptoError::KeyDerivationFailed("OS random number generator unavailable".to_owned())
        })?;
        Ok(Self(bytes))
    }

    /// Reads a salt back from storage.
    ///
    /// Reports only the length mismatch, never the bytes.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        let bytes: [u8; SALT_LEN] = bytes.try_into().map_err(|_| {
            CryptoError::InvalidInput(format!(
                "salt must be {SALT_LEN} bytes, got {}",
                bytes.len()
            ))
        })?;
        Ok(Self(bytes))
    }

    /// Borrows the salt bytes.
    pub fn as_bytes(&self) -> &[u8; SALT_LEN] {
        &self.0
    }
}

define_secret_key! {
    /// The key derived from the master password. Never leaves the device and
    /// is never transmitted; everything else in the hierarchy hangs off it.
    MasterKey, MASTER_KEY_LEN
}

// TODO(phase1): `MasterKey::derive(password: &str, salt: &Salt, params: &Argon2Params)`
// via `argon2::Argon2::hash_password_into`, validating params first and
// mapping every argon2 error to `KeyDerivationFailed` without echoing the
// password. Tests: same salt → same key, different salt → different key,
// known-answer vector, params below the floor rejected.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_params_clear_the_owasp_floor() {
        let params = Argon2Params::default();
        params.validate().unwrap();
        assert!(params.memory_kib >= MIN_MEMORY_KIB);
        assert!(params.iterations >= MIN_ITERATIONS);
    }

    #[test]
    fn weak_params_are_rejected() {
        let weak = Argon2Params {
            memory_kib: 1024,
            iterations: 1,
            parallelism: 0,
        };
        assert!(weak.validate().is_err());
    }

    #[test]
    fn generated_salts_differ() {
        let a = Salt::generate().unwrap();
        let b = Salt::generate().unwrap();
        assert_ne!(a, b, "two CSPRNG salts must not collide");
    }

    #[test]
    fn salt_round_trips_through_bytes() {
        let salt = Salt::generate().unwrap();
        let restored = Salt::from_bytes(salt.as_bytes()).unwrap();
        assert_eq!(salt, restored);
    }

    #[test]
    fn salt_rejects_wrong_length() {
        assert!(Salt::from_bytes(&[0u8; SALT_LEN - 1]).is_err());
        assert!(Salt::from_bytes(&[0u8; SALT_LEN + 1]).is_err());
    }

    #[test]
    fn master_key_debug_is_redacted() {
        let key = MasterKey::from_bytes([7u8; MASTER_KEY_LEN]);
        let rendered = format!("{key:?}");
        assert_eq!(rendered, "MasterKey([REDACTED])");
        assert!(!rendered.contains('7'));
    }
}
